---
builds:
  - id: name-service
    main: ./cmd/name-service
    dir: .
    env:
      - CGO_ENABLED=0
defaultPlatforms:
  - linux/amd64
  - linux/arm64
defaultBaseImage: gcr.io/distroless/static:nonroot
