---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - konfig.yaml
namespace: names
resources:
  - ../base
configMapGenerator:
  - name: name-service-config
    envs:
      - config.env
secretGenerator:
  - name: name-service-secrets
    envs:
      - secrets.env
transformers:
  - image.yaml
