// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: fillmore_labs/name_service/v1alpha1/service.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TBD.
type AddNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Given name.
	GivenName string `protobuf:"bytes,1,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	// Surname.
	Surname *string `protobuf:"bytes,2,opt,name=surname,proto3,oneof" json:"surname,omitempty"`
}

func (x *AddNameRequest) Reset() {
	*x = AddNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fillmore_labs_name_service_v1alpha1_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNameRequest) ProtoMessage() {}

func (x *AddNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fillmore_labs_name_service_v1alpha1_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNameRequest.ProtoReflect.Descriptor instead.
func (*AddNameRequest) Descriptor() ([]byte, []int) {
	return file_fillmore_labs_name_service_v1alpha1_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddNameRequest) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *AddNameRequest) GetSurname() string {
	if x != nil && x.Surname != nil {
		return *x.Surname
	}
	return ""
}

// TBD.
type AddNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddNameResponse) Reset() {
	*x = AddNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fillmore_labs_name_service_v1alpha1_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNameResponse) ProtoMessage() {}

func (x *AddNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fillmore_labs_name_service_v1alpha1_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNameResponse.ProtoReflect.Descriptor instead.
func (*AddNameResponse) Descriptor() ([]byte, []int) {
	return file_fillmore_labs_name_service_v1alpha1_service_proto_rawDescGZIP(), []int{1}
}

// TBD.
type ListNamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListNamesRequest) Reset() {
	*x = ListNamesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fillmore_labs_name_service_v1alpha1_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamesRequest) ProtoMessage() {}

func (x *ListNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fillmore_labs_name_service_v1alpha1_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamesRequest.ProtoReflect.Descriptor instead.
func (*ListNamesRequest) Descriptor() ([]byte, []int) {
	return file_fillmore_labs_name_service_v1alpha1_service_proto_rawDescGZIP(), []int{2}
}

// TBD.
type ListNamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Given name.
	GivenName string `protobuf:"bytes,1,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	// Surname.
	Surname *string `protobuf:"bytes,2,opt,name=surname,proto3,oneof" json:"surname,omitempty"`
}

func (x *ListNamesResponse) Reset() {
	*x = ListNamesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fillmore_labs_name_service_v1alpha1_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamesResponse) ProtoMessage() {}

func (x *ListNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fillmore_labs_name_service_v1alpha1_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamesResponse.ProtoReflect.Descriptor instead.
func (*ListNamesResponse) Descriptor() ([]byte, []int) {
	return file_fillmore_labs_name_service_v1alpha1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListNamesResponse) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *ListNamesResponse) GetSurname() string {
	if x != nil && x.Surname != nil {
		return *x.Surname
	}
	return ""
}

var File_fillmore_labs_name_service_v1alpha1_service_proto protoreflect.FileDescriptor

var file_fillmore_labs_name_service_v1alpha1_service_proto_rawDesc = []byte{
	0x0a, 0x31, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x6f, 0x72, 0x65, 0x5f, 0x6c, 0x61, 0x62, 0x73, 0x2f,
	0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x23, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x6f, 0x72, 0x65, 0x5f, 0x6c, 0x61,
	0x62, 0x73, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x22, 0x5a, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x69,
	0x76, 0x65, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x67, 0x69, 0x76, 0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x73, 0x75, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x73, 0x75, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5d, 0x0a, 0x11, 0x4c,
	0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x69, 0x76, 0x65, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x69, 0x76, 0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x0a, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a,
	0x0a, 0x08, 0x5f, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x85, 0x02, 0x0a, 0x0b, 0x4e,
	0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x76, 0x0a, 0x07, 0x41, 0x64,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x2e, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x6f, 0x72, 0x65,
	0x5f, 0x6c, 0x61, 0x62, 0x73, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x66, 0x69, 0x6c,
	0x6c, 0x6d, 0x6f, 0x72, 0x65, 0x5f, 0x6c, 0x61, 0x62, 0x73, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2e, 0x41, 0x64, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x7e, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12,
	0x35, 0x2e, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x6f, 0x72, 0x65, 0x5f, 0x6c, 0x61, 0x62, 0x73, 0x2e,
	0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x6f, 0x72,
	0x65, 0x5f, 0x6c, 0x61, 0x62, 0x73, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x25, 0x5a, 0x23, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x6f, 0x72, 0x65, 0x2d, 0x6c,
	0x61, 0x62, 0x73, 0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_fillmore_labs_name_service_v1alpha1_service_proto_rawDescOnce sync.Once
	file_fillmore_labs_name_service_v1alpha1_service_proto_rawDescData = file_fillmore_labs_name_service_v1alpha1_service_proto_rawDesc
)

func file_fillmore_labs_name_service_v1alpha1_service_proto_rawDescGZIP() []byte {
	file_fillmore_labs_name_service_v1alpha1_service_proto_rawDescOnce.Do(func() {
		file_fillmore_labs_name_service_v1alpha1_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_fillmore_labs_name_service_v1alpha1_service_proto_rawDescData)
	})
	return file_fillmore_labs_name_service_v1alpha1_service_proto_rawDescData
}

var file_fillmore_labs_name_service_v1alpha1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fillmore_labs_name_service_v1alpha1_service_proto_goTypes = []interface{}{
	(*AddNameRequest)(nil),    // 0: fillmore_labs.name_service.v1alpha1.AddNameRequest
	(*AddNameResponse)(nil),   // 1: fillmore_labs.name_service.v1alpha1.AddNameResponse
	(*ListNamesRequest)(nil),  // 2: fillmore_labs.name_service.v1alpha1.ListNamesRequest
	(*ListNamesResponse)(nil), // 3: fillmore_labs.name_service.v1alpha1.ListNamesResponse
}
var file_fillmore_labs_name_service_v1alpha1_service_proto_depIdxs = []int32{
	0, // 0: fillmore_labs.name_service.v1alpha1.NameService.AddName:input_type -> fillmore_labs.name_service.v1alpha1.AddNameRequest
	2, // 1: fillmore_labs.name_service.v1alpha1.NameService.ListNames:input_type -> fillmore_labs.name_service.v1alpha1.ListNamesRequest
	1, // 2: fillmore_labs.name_service.v1alpha1.NameService.AddName:output_type -> fillmore_labs.name_service.v1alpha1.AddNameResponse
	3, // 3: fillmore_labs.name_service.v1alpha1.NameService.ListNames:output_type -> fillmore_labs.name_service.v1alpha1.ListNamesResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fillmore_labs_name_service_v1alpha1_service_proto_init() }
func file_fillmore_labs_name_service_v1alpha1_service_proto_init() {
	if File_fillmore_labs_name_service_v1alpha1_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fillmore_labs_name_service_v1alpha1_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fillmore_labs_name_service_v1alpha1_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fillmore_labs_name_service_v1alpha1_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNamesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fillmore_labs_name_service_v1alpha1_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNamesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_fillmore_labs_name_service_v1alpha1_service_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_fillmore_labs_name_service_v1alpha1_service_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fillmore_labs_name_service_v1alpha1_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fillmore_labs_name_service_v1alpha1_service_proto_goTypes,
		DependencyIndexes: file_fillmore_labs_name_service_v1alpha1_service_proto_depIdxs,
		MessageInfos:      file_fillmore_labs_name_service_v1alpha1_service_proto_msgTypes,
	}.Build()
	File_fillmore_labs_name_service_v1alpha1_service_proto = out.File
	file_fillmore_labs_name_service_v1alpha1_service_proto_rawDesc = nil
	file_fillmore_labs_name_service_v1alpha1_service_proto_goTypes = nil
	file_fillmore_labs_name_service_v1alpha1_service_proto_depIdxs = nil
}
